[phases.setup]
nixPkgs = [
  "python310",        # Python 3.10 with pip
  "pango",
  "cairo",
  "gdk-pixbuf",
  "libffi",
  "libpng",
  "libjpeg",
  "zlib",
  "gobject-introspection",
  "glib",
  "fontconfig",
  "freetype"
]

[phases.install]
cmds = [
  # just install packages from requirements.txt
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"